# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:latest AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun --bun install --frozen-lockfile

# install with --production (exclude devDependencies)
# RUN mkdir -p /temp/prod
# COPY package.json bun.lockb /temp/prod/
# RUN cd /temp/prod && bun install --frozen-lockfile --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
WORKDIR /usr/src/app
COPY --chown=bun:bun --from=install /temp/dev/node_modules node_modules
COPY . /usr/src/app/

# RUN bun test
RUN bun --bun run build

# run the app
RUN chown bun:bun /usr/src/app
USER bun
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "--bun" , "run", "serve"]